 -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P-2jJ4Dg0ClSfqvvmdnMep_MZghSP-3h
"""

!pip install pip==23.2.1

!pip install fairseq

#@title 1. Montar Google Drive y subir archivos
from google.colab import drive
drive.mount('/content/drive')

# Sube tus archivos manualmente o colócalos en tu Drive
# Ejemplo: /content/drive/MyDrive/Edificio Balcones de Santa Teresa.m4a
# Ejemplo: /content/drive/MyDrive/Slow song (Vocal swap).wav

# Commented out IPython magic to ensure Python compatibility.
#@title 2. Instalar Demucs y so-vits-svc
!pip install demucs
!git clone https://github.com/svc-develop-team/so-vits-svc
# %cd so-vits-svc
!pip install -r requirements.txt
# %cd /content

#@title 3. Separar voces de la canción con Demucs
!demucs "Slow song (Vocal swap).wav" -o /content/separated

# Las voces estarán en /content/separated/htdemucs/Slow song (Vocal swap)/vocals.wav
# El acompañamiento en /content/separated/htdemucs/Slow song (Vocal swap)/accompaniment.wav

#@title 4. Preparar datos para so-vits-svc
import os
import shutil

os.makedirs('/content/so-vits-svc/dataset_raw/mi_voz', exist_ok=True)
shutil.copy('/content/drive/MyDrive/Edificio Balcones de Santa Teresa.m4a', '/content/so-vits-svc/dataset_raw/mi_voz/')

!apt-get install ffmpeg -y
!ffmpeg -i "/content/so-vits-svc/dataset_raw/mi_voz/Edificio Balcones de Santa Teresa.m4a" "/content/so-vits-svc/dataset_raw/mi_voz/Edificio Balcones de Santa Teresa.wav"

import os
os.remove("/content/so-vits-svc/dataset_raw/mi_voz/Edificio Balcones de Santa Teresa.m4a")

# Commented out IPython magic to ensure Python compatibility.
# Esto convertirá todos los audios en dataset_raw a 44100 Hz y los pondrá en dataset/44k
# %cd /content/so-vits-svc
!python resample.py

!pip install loguru
!python preprocess_flist_config.py

!pip install fairseq

!pip install faiss-cpu
!python preprocess_hubert_f0.py

#@title 5. Entrenar el modelo de clonación de voz (puede tardar horas)
# Puedes ajustar el config.json según tus necesidades
!python train.py --config configs/config.json

#@title 6. Inferencia: transformar la voz original de la canción por la tuya
# Ajusta las rutas según corresponda
!python inference_main.py \
  -m /content/so-vits-svc/logs/44k/your_model.pth \
  -c /content/so-vits-svc/configs/config.json \
  -n /content/separated/htdemucs/Slow\ song\ \(Vocal\ swap\)/vocals.wav \
  -o /content/vocals_tu_voz.wav

#@title 7. Mezclar la voz clonada con la música
!pip install pydub
!apt-get install ffmpeg -y
from pydub import AudioSegment

voz = AudioSegment.from_wav("/content/vocals_tu_voz.wav")
musica = AudioSegment.from_wav("/content/separated/htdemucs/Slow song (Vocal swap)/accompaniment.wav")

# Ajusta volúmenes si es necesario
voz = voz - 2
musica = musica - 1

final = musica.overlay(voz)
final.export("/content/cancion_final.wav", format="wav")

import os
print(os.listdir('/content/so-vits-svc'))

print(os.listdir('/content/so-vits-svc/tools'))
print(os.listdir('/content/so-vits-svc/scripts'))